import type { PermissionEffect } from "@bridge/spec";
import type { z } from "zod";

/**
 * Tool adapter contract (ADR-0007). Native tools, MCP-exposed tools, and
 * custom user tools all implement this. Tools receive a context that carries
 * the permission check — they cannot bypass the permission engine.
 */

export interface ToolAction {
  name: string;
  /** Dangerous actions get "ask" rules generated by the compiler unless explicitly allowed. */
  dangerous?: boolean;
}

export interface ToolContext {
  workspaceId: string;
  agentId: string;
  runId: string;
  log: (message: string, data?: Record<string, unknown>) => void;
  /** Evaluates the run's permission policy for `tool:<name>` + action. */
  checkPermission: (action: string) => PermissionEffect;
}

export interface ToolResult {
  ok: boolean;
  output: unknown;
  error?: string;
}

export interface BridgeTool<Input = unknown> {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: z.ZodType<Input>;
  /**
   * JSON Schema advertised to models. Derived from `inputSchema` when absent;
   * set it when the authoritative schema comes from elsewhere (an MCP server
   * publishes its own) so parameter names survive the round trip.
   */
  readonly jsonSchema?: Record<string, unknown>;
  readonly actions: ToolAction[];
  /**
   * Which declared action this input performs — reading a file and deleting
   * one are the same tool but not the same permission. The runtime calls this
   * *before* executing so a decision (allow / deny / ask) can be made without
   * side effects. Defaults to the first declared action.
   */
  actionFor?(input: Input): string;
  execute(input: Input, ctx: ToolContext): Promise<ToolResult>;
}
