import type { PermissionEffect } from "@bridge/spec";
import type { z } from "zod";

/**
 * Tool adapter contract (ADR-0007). Native tools, MCP-exposed tools, and
 * custom user tools all implement this. Tools receive a context that carries
 * the permission check — they cannot bypass the permission engine.
 */

export interface ToolAction {
  name: string;
  /** Dangerous actions get "ask" rules generated by the compiler unless explicitly allowed. */
  dangerous?: boolean;
}

export interface ToolContext {
  workspaceId: string;
  agentId: string;
  runId: string;
  log: (message: string, data?: Record<string, unknown>) => void;
  /** Evaluates the run's permission policy for `tool:<name>` + action. */
  checkPermission: (action: string) => PermissionEffect;
}

export interface ToolResult {
  ok: boolean;
  output: unknown;
  error?: string;
}

export interface BridgeTool<Input = unknown> {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: z.ZodType<Input>;
  readonly actions: ToolAction[];
  execute(input: Input, ctx: ToolContext): Promise<ToolResult>;
}
